version: "3.7"

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Superl33tpassw0rd!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  backend:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - db